---
# default source for environment variables
env_vars:
  DEFAULT_NEWRELIC_ENVIRONMENT_VARIABLE: Wh0r3l1sh?r3lic
  apache_vhosts:
    - servername: "local.dev"

#    PATH: /usr/local/
#    http_proxy: http://
#    https_proxy: https://
